language: perl
perl:
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - "HARNESS_OPTIONS=j9 TEST_EV=1"
install:
  - "cpanm -n EV"
  - "cpanm -n --installdeps ."
notifications:
  email: sugama@jamadam.com
