language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
branches:
  only:
    - mojo-legacy
env:
  - "HARNESS_OPTIONS=j9 TEST_EV=1 TEST_SOCKS=1 TEST_TLS=1"
install:
  - "cpanm -n EV IO::Socket::Socks IO::Socket::SSL"
  - "cpanm -n --installdeps ."
notifications:
  email: sugama@jamadam.com
